# Generated by Django 4.2.13 on 2024-06-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20240622_1425"),
    ]

    operations = [
        migrations.AddField(
            model_name="intriguer",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="/brandPlaceholder.jpg", null=True, upload_to=""
            ),
        ),
    ]
